import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {/* <Script
          id="msg91-config"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              var configuration = {
                widgetId: "35646f734664363237393433",
                tokenAuth: "446854TbbIRrdl67feb4ddP1",
                exposeMethods: "false",
                success: (data) => {
                    console.log('success response', data);
                },
                failure: (error) => {
                    console.log('failure reason', error);
                },
                "VAR1": "<VAR1>"
              };
            `,
          }}
        />
          <Script
          id="msg91-otp"
          strategy="afterInteractive"
          src="https://verify.msg91.com/otp-provider.js"
          onLoad="initSendOTP(configuration)"
        /> */}
        {children}
      </body>
    </html>
  );
}
